feat: add exporting android bindings
vimwitch/mopro pull request #1
Opened 2024-06-28 15:27 UTC by vivianjeng

- it should output a `jniLibs/` folder and a `uniffi/mopro` folder in `MoproAndroidBindings` direcotry
- ref
    - https://zkmopro.org/docs/circom/android#getting-started-with-exported-bindings
    - https://forgen.tech/en/blog/post/building-an-android-app-with-rust-using-uniffi
    - https://sal.dev/android/intro-rust-android-uniffi/
- not sure if there is a way to create like `xcframework`
- don't know what is the difference between the ios `framework_out` and `framework_dest`?

2024-06-28 19:53 UTC, vimwitch commented
> don't know what is the difference between the ios `framework_out` and `framework_dest`?

`framework_out` is a temporary directory where build intermediates are stored. This is so if the process crashes or is killed the final destination doesn't contain a half complete build. When the build is done it's moved to `framework_dest` using an atomic operation, so it either succeeds or nothing happens.

2024-06-28 22:19 UTC, vimwitch requested changes
This PR looks great, i managed to use it to build the library and make a proof in an android app. Just some changes to filenames and what directories are used.

2024-06-28 22:19 UTC, vimwitch commented on mopro-ffi/src/app_config/android.rs
> +            "{}/{}/{}/libmopro_bindings.so",
I managed to integrate this output into an android app. We need to name the output libraries `libuniffi_mopro.so` in order for it to build.

2024-06-28 22:19 UTC, vimwitch commented on mopro-ffi/src/app_config/android.rs
> +        if !bindings_dest.exists() {
Try to use `bindings_out` for these operations. As the final step you should move `bindings_out` to `bindings_dest` using `fs::rename`. `bindings_out` is an empty temporary directory, so you don't need to worry about checking for existing files, you can just write.

2024-06-28 22:19 UTC, vimwitch commented on mopro-ffi/src/app_config/android.rs
> +            "jniLibs/{}/libmopro_bindings.so",
Should be `libuniffi_mopro.so`

2024-06-28 22:19 UTC, vimwitch commented on mopro-ffi/src/app_config/android.rs
> +        if !bindings_dest
Write to `bindings_out` and you can remove the `exists` if statements and just `create_dir_all` then `write`.

2024-06-28 22:19 UTC, vimwitch commented on mopro-ffi/src/app_config/android.rs
> +        .expect("Failed to write mopro.swift");
At the end of this function you should call `cleanup_tmp_local` from the `mod.rs`. It will remove all temporary directories made with `mktemp_local`.

2024-06-28 23:07 UTC, vimwitch commented on mopro-ffi/src/app_config/android.rs
> +        if !bindings_dest.join(Path::new("jniLibs")).exists() {
Once other thing, you don't need the `Path::new` when you call `join`. You can do `bindings_dest.join("jniLibs")`

2024-06-29 00:48 UTC, vimwitch commented
I've got the android app fully compiling in the ci in vimwitch/mopro-app#1. Once we merge both of these the system should be fully functional. Then we just need to write docs 🎉

2024-07-01 11:37 UTC, vivianjeng commented on mopro-ffi/src/app_config/android.rs
> +            "jniLibs/{}/libmopro_bindings.so",
I think there should be some settings in uniffi-bindgen to sync the library name
since we previously use `libuniffi_mopro` and put it in `uniffi/mopro/mopro.kt`
I think something is changed to `mopro_bindings` so the binary output is still `libmopro_bindings`
and maybe we should put it in other directory (not `uniffi/mopro/`)

Just take a note here
we can still keep the output `libuniffi_mopro.so` and put it in directory `uniffi/mopro/`
if it is confusing for people (even for me) we can change later

2024-07-01 11:59 UTC, vimwitch commented on mopro-ffi/src/app_config/android.rs
> +            "jniLibs/{}/libmopro_bindings.so",
This part is tricky, the library name is different depending on iOS or android. On iOS i think the library filename is specified in `info.plist` so we can leave it as `mopro_bindings`. On android they do it based on the folder structure, so `uniffi/mopro/*.so` requires the library be named `libuniffi_mopro`.

In the uniffi code we setup the [scaffolding](https://github.com/vimwitch/mopro/blob/main/mopro-ffi/src/lib.rs#L185) for `mopro`, but using the udl we generate swift/kotlin bindings for `mopro_bindings` because the app cannot be named `mopro` 😕

2024-07-01 12:03 UTC, merged